### PR TITLE
Support text-2.0

### PR DESCRIPTION
**Pull request by Bodigrim**
Tested with 
```cabal
packages: .
constraints: text >= 2.0
```

### CODE REVIEW

**Comment by tittoassini** [comment]
Thanks Bodigrim, I am going to release a new version of flat this month and it will include your changes. 

Best

**Comment by Bodigrim** [comment]
`text-2.0` is finally released: https://hackage.haskell.org/package/text-2.0

**Comment by Bodigrim** [comment]
@tittoassini just a gentle reminder about this PR.

**Comment by tittoassini** [comment]
Sorry for the delay, I hope to get a new version out by the 15th of February (and to be a lot more responsive in the future).

**Comment by Bodigrim** [comment]
@tittoassini just a friendly reminder.

**Comment by tittoassini** [comment]
Huge apologies for the incredible delay in handling this !

**Pull request merged**
